=== pete88b/plsql-core/trunk/plsql-core-maven-tools/trunk/src/main/resources/com/butterfill/plsqlcore/maven/xml/plsql-core-module.xsd
<?xml version="1.0" encoding="windows-1252"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://plsql-core.butterfill.com/schema/plsql-core-module"
            xmlns:tns="http://plsql-core.butterfill.com/schema/plsql-core-module"
            elementFormDefault="qualified">
    <xsd:element name="plsql-core-module">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="location" type="xsd:anyURI"/>
                <xsd:element name="version" type="tns:moduleVersionType"/>
                <xsd:element name="file-set">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="file" type="xsd:string" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="dependencies" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="dependency" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="location" type="xsd:anyURI"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <!-- 
    module versions consist of at least one period, letter, didgit, underscore or hyphen 
    -->
    <xsd:simpleType name="moduleVersionType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([\.a-zA-Z0-9_\-])+"/>
        </xsd:restriction>
    </xsd:simpleType>
    
</xsd:schema>

=== pete88b/plsql-core/tags/v0.1/plsql-core/src/main/sql/exceptions/plsql-core-module.xml
<?xml version="1.0" encoding="windows-1252"?>
<plsql-core-module  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://plsql-core.butterfill.com/schema/plsql-core-module'
   xsi:schemaLocation='http://plsql-core.butterfill.com/schema/plsql-core-module plsql-core-module.xsd'>
    <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/src/main/sql/exceptions/</location>
    <version>0.1</version>
    <file-set>
        <file>build.sql</file>
        <file>drop.sql</file>
        <file>index.html</file>
        <file>exceptions.pck</file>
    </file-set>
    <dependencies>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/src/main/sql/logger/</location>
        </dependency>
    </dependencies>
</plsql-core-module>

=== pete88b/plsql-core/trunk/plsql-core/src/main/sql/constants/plsql-core-module.xml
<?xml version="1.0" encoding="windows-1252"?>
<plsql-core-module  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://plsql-core.butterfill.com/schema/plsql-core-module'
   xsi:schemaLocation='http://plsql-core.butterfill.com/schema/plsql-core-module plsql-core-module.xsd'>
    <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/src/main/sql/constants/</location>
    <version>0.1</version>
    <file-set>
        <file>build.sql</file>
        <file>drop.sql</file>
        <file>index.html</file>
        <file>constants.spc</file>
    </file-set>
</plsql-core-module>

=== pete88b/plsql-core/tags/v0.2/plsql-core/src/main/sql/permissions/plsql-core-module.xml
<?xml version="1.0" encoding="windows-1252"?>
<plsql-core-module  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://plsql-core.butterfill.com/schema/plsql-core-module'
   xsi:schemaLocation='http://plsql-core.butterfill.com/schema/plsql-core-module plsql-core-module.xsd'>
    <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/permissions/</location>
    <version>0.1</version>
    <file-set>
        <file>build.sql</file>
        <file>drop.sql</file>
        <file>index.html</file>
        <file>permission.spc</file>
        <file>permission.bdy</file>
        <file>permissions.spc</file>
        <file>permissions.bdy</file>
    </file-set>
    <dependencies>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/logger/</location>
        </dependency>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/messages/</location>
        </dependency>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/exceptions/</location>
        </dependency>
    </dependencies>
</plsql-core-module>

=== pete88b/plsql-core/trunk/plsql-core/src/main/sql/logger/plsql-core-module.xml
<?xml version="1.0" encoding="windows-1252"?>
<plsql-core-module  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://plsql-core.butterfill.com/schema/plsql-core-module'
   xsi:schemaLocation='http://plsql-core.butterfill.com/schema/plsql-core-module plsql-core-module.xsd'>
    <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/sql/logger/</location>
    <version>0.1</version>
    <file-set>
        <file>build.sql</file>
        <file>drop.sql</file>
        <file>index.html</file>
        <file>logger.bdy</file>
        <file>logger.spc</file>
        <file>logger_error.spc</file>
        <file>logger_error_post_10.bdy</file>
        <file>logger_error_pre_10.bdy</file>
        <file>logger_feedback.bdy</file>
        <file>logger_feedback.spc</file>
        <file>logger_stack_utils.bdy</file>
        <file>logger_stack_utils.spc</file>
        <file>logger_utils.bdy</file>
        <file>logger_utils.spc</file>
    </file-set>
</plsql-core-module>

=== pete88b/plsql-core/plsql-core/trunk/src/main/resources/plsql/event_mediator/plsql-core-module.xml
<?xml version="1.0" encoding="windows-1252"?>
<plsql-core-module  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://plsql-core.butterfill.com/schema/plsql-core-module'
   xsi:schemaLocation='http://plsql-core.butterfill.com/schema/plsql-core-module plsql-core-module.xsd'>
    <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/event_mediatorXXX/</location>
    <version>0.1</version>
    <file-set>
        <file>build.sql</file>
        <file>event_mediator.pck</file>
    </file-set>
    <dependencies>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/logger/</location>
        </dependency>
    </dependencies>
</plsql-core-module>

=== pete88b/plsql-core/trunk/plsql-core/trunk/src/main/resources/plsql/properties/utilities/plsql-core-module.xml
<?xml version="1.0" encoding="windows-1252"?>
<plsql-core-module  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://plsql-core.butterfill.com/schema/plsql-core-module'
   xsi:schemaLocation='http://plsql-core.butterfill.com/schema/plsql-core-module plsql-core-module.xsd'>
    <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/properties/utilities/</location>
    <version>0.1</version>
    <file-set>
        <file>extract-to-java.sql</file>
        <file>extract-to-plsql.sql</file>
    </file-set>
    <dependencies>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/trunk/src/main/resources/plsql/properties/</location>
        </dependency>
    </dependencies>
</plsql-core-module>

=== pete88b/plsql-core/trunk/plsql-core/src/main/sql/properties/admin/plsql-core-module.xml
<?xml version="1.0" encoding="windows-1252"?>
<plsql-core-module  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://plsql-core.butterfill.com/schema/plsql-core-module'
   xsi:schemaLocation='http://plsql-core.butterfill.com/schema/plsql-core-module plsql-core-module.xsd'>
    <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/src/main/sql/properties/admin/</location>
    <version>0.1</version>
    <file-set>
        <file>build.sql</file>
        <file>drop.sql</file>
        <file>index.html</file>
        <file>property_group.spc</file>
        <file>property_group.bdy</file>
        <file>property_key.spc</file>
        <file>property_key.bdy</file>
        <file>property_value.spc</file>
        <file>property_value.bdy</file>
    </file-set>
    <dependencies>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/src/main/sql/properties/</location>
        </dependency>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/src/main/sql/logger/</location>
        </dependency>
        <dependency>
            <location>http://plsql-core.googlecode.com/svn/trunk/plsql-core/src/main/sql/messages/</location>
        </dependency>
    </dependencies>
</plsql-core-module>
